-- Generated by `forge db migrate compose`. Do not edit — change schema.sql and compose again.
-- forge:compose {"desired":{"node_modules/@y-core/forge/src/auth/schema.sql":"871cc7d46e2a8aa647cca3df4d55ec3beba38b5d7cef67b2ee95d0ac3be75f63","config/schema.sql":"75ed3a8c81e81c552bb5ad15763ab5de42b20a3ec7244ec1ad36c71e1ad06cd1"},"baseline":"e1c0de49a3a7acddea5bd7807eecfef19f803d512e81071c903dd42c08b543c4","body":"a9f61e54933366d9274709468a7c7cd819c8e25638103d5db3366dd0ee9747e5","forge":"0.2.5"}
PRAGMA defer_foreign_keys = true;

CREATE TABLE "_forge_new_auth_factors" (
  id BLOB PRIMARY KEY NOT NULL,
  user_id BLOB NOT NULL REFERENCES auth_users (id) ON DELETE CASCADE,
  kind TEXT NOT NULL,
  
  secret BLOB,
  
  last_counter INTEGER,
  
  
  failed_attempts INTEGER NOT NULL DEFAULT 0,
  
  
  last_verified_at INTEGER,
  confirmed_at INTEGER,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
) STRICT;

INSERT INTO "_forge_new_auth_factors" ("id", "user_id", "kind", "secret", "last_counter", "failed_attempts", "confirmed_at", "created_at", "updated_at") SELECT "id", "user_id", "kind", "secret", "last_counter", "failed_attempts", "confirmed_at", "created_at", "updated_at" FROM "auth_factors";

DROP TABLE "auth_factors";

ALTER TABLE "_forge_new_auth_factors" RENAME TO "auth_factors";

CREATE UNIQUE INDEX auth_factors_user_kind ON auth_factors (user_id, kind);
