-- Generated by `forge db migrate compose`. Do not edit — change schema.sql and compose again.
-- forge:compose {"desired":{"node_modules/@y-core/forge/src/auth/schema.sql":"871cc7d46e2a8aa647cca3df4d55ec3beba38b5d7cef67b2ee95d0ac3be75f63"},"baseline":"c644688ba6cc2ec5068ea5bbcaa05e9c82bd98e86cad48633914ce410251a217","body":"75863e7bd3e577450367d4865c8af3032ceb7b6b4206b91a93d34e6492698d95","forge":"0.3.0"}
PRAGMA defer_foreign_keys = true;

DROP TABLE IF EXISTS "preferences";
