-- Generated by `forge db migrate compose`. Do not edit — change schema.sql and compose again.
-- forge:compose {"desired":{"node_modules/@y-core/forge/src/auth/schema.sql":"b3758d53f64813c100906f6567ba4356148c4303ba0e7fd715a56ab32b3feca3","config/schema.sql":"75ed3a8c81e81c552bb5ad15763ab5de42b20a3ec7244ec1ad36c71e1ad06cd1"},"baseline":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","body":"d7a318536d4924acf750b23ed2a1a9db8cf65878b5eb168ff5e413342b2bce24","forge":"0.1.10"}
PRAGMA defer_foreign_keys = true;

CREATE TABLE auth_challenges (
  key TEXT PRIMARY KEY NOT NULL,
  value TEXT NOT NULL,
  expires_at INTEGER NOT NULL
) STRICT;

CREATE TABLE auth_nonces (
  key TEXT PRIMARY KEY NOT NULL,
  expires_at INTEGER NOT NULL
) STRICT;

CREATE TABLE auth_users (
  id BLOB PRIMARY KEY NOT NULL,
  email TEXT NOT NULL,
  
  
  email_key TEXT NOT NULL,
  email_verified_at INTEGER,
  
  
  webauthn_id BLOB,
  is_admin INTEGER NOT NULL DEFAULT 0,
  deactivated_at INTEGER,
  
  
  sessions_invalid_before INTEGER,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  
  
  CHECK (length(email) <= 254 AND length(email_key) <= 254)
) STRICT;

CREATE TABLE auth_credentials (
  id BLOB PRIMARY KEY NOT NULL,
  user_id BLOB NOT NULL REFERENCES auth_users (id) ON DELETE CASCADE,
  
  credential_id TEXT NOT NULL,
  public_key BLOB NOT NULL,
  algorithm INTEGER NOT NULL,
  sign_count INTEGER NOT NULL DEFAULT 0,
  transports TEXT,
  backup_eligible INTEGER NOT NULL DEFAULT 0,
  backed_up INTEGER NOT NULL DEFAULT 0,
  label TEXT,
  last_used_at INTEGER,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
) STRICT;

CREATE TABLE auth_factors (
  id BLOB PRIMARY KEY NOT NULL,
  user_id BLOB NOT NULL REFERENCES auth_users (id) ON DELETE CASCADE,
  kind TEXT NOT NULL,
  
  secret BLOB,
  
  last_counter INTEGER,
  
  
  failed_attempts INTEGER NOT NULL DEFAULT 0,
  confirmed_at INTEGER,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
) STRICT;

CREATE TABLE auth_identity_links (
  id BLOB PRIMARY KEY NOT NULL,
  user_id BLOB NOT NULL REFERENCES auth_users (id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  subject TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
) STRICT;

CREATE TABLE auth_otp_state (
  user_id BLOB PRIMARY KEY NOT NULL REFERENCES auth_users (id) ON DELETE CASCADE,
  
  token TEXT NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  issued_at INTEGER NOT NULL,
  expires_at INTEGER NOT NULL
) STRICT;

CREATE TABLE preferences (
  
  user_id BLOB PRIMARY KEY NOT NULL REFERENCES auth_users (id) ON DELETE CASCADE,
  theme TEXT NOT NULL DEFAULT 'system',
  updated_at INTEGER NOT NULL,
  CHECK (theme IN ('system', 'light', 'dark'))
) STRICT;

CREATE INDEX auth_challenges_expires_at ON auth_challenges (expires_at);

CREATE UNIQUE INDEX auth_credentials_credential_id ON auth_credentials (credential_id);

CREATE INDEX auth_credentials_user_id ON auth_credentials (user_id);

CREATE UNIQUE INDEX auth_factors_user_kind ON auth_factors (user_id, kind);

CREATE UNIQUE INDEX auth_identity_links_provider_subject ON auth_identity_links (provider, subject);

CREATE INDEX auth_identity_links_user_id ON auth_identity_links (user_id);

CREATE INDEX auth_nonces_expires_at ON auth_nonces (expires_at);

CREATE UNIQUE INDEX auth_users_email_key ON auth_users (email_key);

CREATE INDEX auth_users_is_admin ON auth_users (is_admin);

CREATE UNIQUE INDEX auth_users_webauthn_id ON auth_users (webauthn_id);
