/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false ./.types/worker-configuration.d.ts` (hash: b5abdaa7fb111fcd08ea7ce5dbccbe6e)
interface __BaseEnv_Env {
	LOGS_KV: KVNamespace;
	AUTH_KV: KVNamespace;
	AUTH_DB: D1Database;
	RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	SITE_ORIGIN: string;
	LOG_LEVEL: string;
	CSRF_SECRET: string;
	EMAIL_API_KEY: string;
	TURNSTILE_SECRET_KEY: string;
	TURNSTILE_SITE_KEY: string;
	TURNSTILE_DEV_HOSTNAME: string;
	AUTH_KEY_RING: string;
	SESSION_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
