/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false ./.types/worker-configuration.d.ts` (hash: 71a721186c60fa4968067edec37b1312)
interface __BaseEnv_Env {
	LOGS_KV: KVNamespace;
	RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	SITE_ORIGIN: string;
	LOG_LEVEL: string;
	CSRF_SECRET: string;
	EMAIL_API_KEY: string;
	TURNSTILE_SECRET_KEY: string;
	TURNSTILE_SITE_KEY: string;
	TURNSTILE_DEV_HOSTNAME: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
