/* eslint-disable */
// Generated by Wrangler by running `wrangler types ./.types/worker-configuration.d.ts --no-include-runtime` (hash: 34e8fc76c85d964b238acd7d951d85c7)
interface __BaseEnv_Env {
	RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	BASE_URL: "https://example.com";
	EMAIL_FROM: "hello@example.com";
	EMAIL_TO: "hello@example.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
